CREATE TABLE IF NOT EXISTS accounts (
	id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	username varchar(50) NOT NULL,
	password varchar(255) NOT NULL,
	email varchar(100) NOT NULL,
	organisation varchar(100) NOT NULL,
	address varchar(100) NOT NULL,
	city varchar(100) NOT NULL,
	state varchar(100) NOT NULL,
	country varchar(100) NOT NULL,
	postalcode varchar(100) NOT NULL
);